### ISSUE TITLE
Getting the list of keys based on pattern or all.

### ISSUE THREAD

**Issue by dishantmunjal** [microsoft/UnifiedRedisPlatform.Core#3]
Hi
If we have done IDistributedCache implementation, there is currently no method exposed which can give list of all the keys for a particular tenant. 
We would like to request a feature where a method is exposed where we give a pattern (or not for all the keys) and get list of keys following that pattern. 
A pattern could be as simple as *key_containing_this_string* or starting_word_is_this_string* or *ending_word_is_this.

**Comment by patrickCode** [comment]
A new interface has been exposed in the library for this operation. Download the latest NuGet from here --> https://www.nuget.org/packages/DistributedCache.Extensions.UnifiedRedisPlatform/

Sample Code --> https://github.com/microsoft/UnifiedRedisPlatform.Core/blob/main/src/tests/Microsoft.UnifiedRedisPlatform.TestApps/TestWebAppCore.Latest/Controllers/CacheController.cs
