### ISSUE TITLE
Pattern Issue

### ISSUE THREAD

**Issue by dishantmunjal** [microsoft/UnifiedRedisPlatform.Core#6]
pattern search in 
```csharp 
Task<IEnumerable<RedisKey>> GetKeys(string pattern = "");
```
in file - [IDistributedUnifiedRedisCache](https://github.com/microsoft/UnifiedRedisPlatform.Core/blob/main/src/sdk/Extensions/Microsoft.Extensions.Caching.UnifiedRedisPlatform/IDistributedUnifiedRedisCache.cs) is case sensitive. 
For example - if I send *keyword* then any key which has _KeyWord_ sub-string in it wont be returned as it doesn't match the case of _keyword_.
Please look into it and share how to ensure the keyword is checked ignoring the case of the characters.

**Comment by patrickCode** [comment]
Redis is case-sensitive by default. Hence case-sensitive search cannot be supported.
